import type { App, Cookie } from 'electron'
import { session } from 'electron'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

export const YOUTUBE_WEBVIEW_PARTITION = 'persist:whodownloads-youtube'

const NETSCAPE_COOKIE_HEADER = [
  '# Netscape HTTP Cookie File',
  '# This file is generated by WhoDownloads for yt-dlp.',
  ''
].join('\n')

function hasUsefulCookieFields(cookie: Cookie): boolean {
  return Boolean(cookie.domain && cookie.name && typeof cookie.value === 'string')
}

function normalizeCookieDomain(cookie: Cookie): string {
  return cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain
}

function getIncludeSubdomains(cookie: Cookie): string {
  return cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE'
}

function getExpiration(cookie: Cookie): string {
  return typeof cookie.expirationDate === 'number' && Number.isFinite(cookie.expirationDate)
    ? `${Math.trunc(cookie.expirationDate)}`
    : '0'
}

export function serializeCookiesForYtDlp(cookies: Cookie[]): string {
  const lines = cookies
    .filter(hasUsefulCookieFields)
    .map((cookie) =>
      [
        normalizeCookieDomain(cookie),
        getIncludeSubdomains(cookie),
        cookie.path || '/',
        cookie.secure ? 'TRUE' : 'FALSE',
        getExpiration(cookie),
        cookie.name,
        cookie.value
      ].join('\t')
    )

  return `${NETSCAPE_COOKIE_HEADER}\n${lines.join('\n')}${lines.length ? '\n' : ''}`
}

export async function exportYouTubeWebviewCookies(app: App): Promise<string | undefined> {
  const youtubeSession = session.fromPartition(YOUTUBE_WEBVIEW_PARTITION)
  const cookies = await youtubeSession.cookies.get({})
  const usefulCookies = cookies.filter(hasUsefulCookieFields)

  if (usefulCookies.length === 0) {
    return undefined
  }

  const cookieFilePath = join(app.getPath('userData'), 'yt-dlp-youtube-cookies.txt')
  await writeFile(cookieFilePath, serializeCookiesForYtDlp(usefulCookies), 'utf8')

  return cookieFilePath
}

export async function getYtDlpCookieArgs(app: App): Promise<string[]> {
  const cookieFilePath = await exportYouTubeWebviewCookies(app)

  return cookieFilePath ? ['--cookies', cookieFilePath] : []
}
